export const caseList = {
  'process-instance': [
    {
      'process-instance-id': 1,
      'process-id': 'contractor-onboarding-process.contractor-on-boarding',
      'process-name': 'contractor-on-boarding',
      'process-version': '1.0',
      'process-instance-state': 1,
      'container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      initiator: 'rhpamAdmin',
      'start-date': {
        'java.util.Date': 1586892344088,
      },
      'process-instance-desc': 'contractor-on-boarding',
      'correlation-key': 'rh-contractor-onboarding-0000000001',
      'parent-instance-id': -1,
      'sla-compliance': 0,
      'sla-due-date': null,
      'active-user-tasks': null,
      'process-instance-variables': null,
    },
    {
      'process-instance-id': 2,
      'process-id': 'contractor-onboarding-process.contractor-on-boarding',
      'process-name': 'contractor-on-boarding',
      'process-version': '1.0',
      'process-instance-state': 1,
      'container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      initiator: 'rhpamAdmin',
      'start-date': {
        'java.util.Date': 1586892378722,
      },
      'process-instance-desc': 'contractor-on-boarding',
      'correlation-key': 'rh-contractor-onboarding-0000000002',
      'parent-instance-id': -1,
      'sla-compliance': 0,
      'sla-due-date': null,
      'active-user-tasks': null,
      'process-instance-variables': null,
    },
    {
      'process-instance-id': 3,
      'process-id': 'contractor-onboarding-process.contractor-on-boarding',
      'process-name': 'contractor-on-boarding',
      'process-version': '1.0',
      'process-instance-state': 1,
      'container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      initiator: 'rhpamAdmin',
      'start-date': {
        'java.util.Date': 1586892397125,
      },
      'process-instance-desc': 'contractor-on-boarding',
      'correlation-key': 'rh-contractor-onboarding-0000000003',
      'parent-instance-id': -1,
      'sla-compliance': 0,
      'sla-due-date': null,
      'active-user-tasks': null,
      'process-instance-variables': null,
    },
  ],
};
