export const Milestones = [
  {
    'milestone-name': 'contractor_identification_milestone',
    'milestone-id': '3',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
  {
    'milestone-name': 'contractor-onboarding-started',
    'milestone-id': '4',
    'milestone-achieved': true,
    'milestone-achieved-at': 1590401236383,
    'milestone-status': 'Completed',
  },
  {
    'milestone-name': 'serviceNow_account_request_milestone',
    'milestone-id': '_57CCA3EF-659A-4874-B63A-C1584D4ECF89',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
  {
    'milestone-name': 'VAA_creation_milestone',
    'milestone-id': '_2CC07E2D-34A5-4296-AB1A-062E58B202EF',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
  {
    'milestone-name': 'Oracle_account_request_milestone',
    'milestone-id': '_DA1F9B57-9F32-4E08-826E-007F950207D1',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
  {
    'milestone-name': 'PSA_account_request_milestone',
    'milestone-id': '_A17480C9-DE55-4F59-BDFF-B26B96903CB6',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
  {
    'milestone-name': 'VAA_Review_Milestone',
    'milestone-id': '_09E13E26-9A3F-4E43-82C4-EBE2C94285D5',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
  {
    'milestone-name': 'contractor_email_username_token_milestone',
    'milestone-id': '_2C54EFF3-DEC5-443D-8E98-590854FC8350',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
  {
    'milestone-name': 'PSA_account_request_for_Supplier_add',
    'milestone-id': '_4E2D3C1C-007B-4FBD-A436-DCADF6E0D65C',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
  {
    'milestone-name': 'Awaiting_VAA_completion_from_supplier_milestone',
    'milestone-id': '_626BF61D-0CEB-4ACB-8D38-15E1998B597A',
    'milestone-achieved': false,
    'milestone-achieved-at': null,
    'milestone-status': 'Available',
  },
];
