export const taskList = {
  'task-summary': [
    {
      'task-id': 1,
      'task-name': 'Contractor informations',
      'task-subject': null,
      'task-description': 'rh-contractor-onboarding-0000000001::',
      'task-status': 'Completed',
      'task-priority': 0,
      'task-is-skipable': false,
      'task-actual-owner': 'rhpamAdmin',
      'task-created-by': '',
      'task-created-on': {
        'java.util.Date': 1586992635208,
      },
      'task-activation-time': {
        'java.util.Date': 1586992635208,
      },
      'task-expiration-time': null,
      'task-proc-inst-id': 1,
      'task-proc-def-id': 'contractor-onboarding-process.contractor-on-boarding',
      'task-container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      'task-parent-id': -1,
    },
    {
      'task-id': 2,
      'task-name': 'Check contractor informations details',
      'task-subject': null,
      'task-description': 'rh-contractor-onboarding-0000000001::',
      'task-status': 'Reserved',
      'task-priority': 0,
      'task-is-skipable': false,
      'task-actual-owner': 'rhpamAdmin',
      'task-created-by': '',
      'task-created-on': {
        'java.util.Date': 1586992642705,
      },
      'task-activation-time': {
        'java.util.Date': 1586992642705,
      },
      'task-expiration-time': null,
      'task-proc-inst-id': 1,
      'task-proc-def-id': 'contractor-onboarding-process.contractor-on-boarding',
      'task-container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      'task-parent-id': -1,
    },
    {
      'task-id': 3,
      'task-name': 'Contractor informations',
      'task-subject': null,
      'task-description': 'rh-contractor-onboarding-0000000002::',
      'task-status': 'Completed',
      'task-priority': 0,
      'task-is-skipable': false,
      'task-actual-owner': 'rhpamAdmin',
      'task-created-by': '',
      'task-created-on': {
        'java.util.Date': 1586994515434,
      },
      'task-activation-time': {
        'java.util.Date': 1586994515434,
      },
      'task-expiration-time': null,
      'task-proc-inst-id': 2,
      'task-proc-def-id': 'contractor-onboarding-process.contractor-on-boarding',
      'task-container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      'task-parent-id': -1,
    },
    {
      'task-id': 4,
      'task-name': 'Check contractor informations details',
      'task-subject': null,
      'task-description': 'rh-contractor-onboarding-0000000002::',
      'task-status': 'Reserved',
      'task-priority': 0,
      'task-is-skipable': false,
      'task-actual-owner': 'rhpamAdmin',
      'task-created-by': '',
      'task-created-on': {
        'java.util.Date': 1586994520339,
      },
      'task-activation-time': {
        'java.util.Date': 1586994520339,
      },
      'task-expiration-time': null,
      'task-proc-inst-id': 2,
      'task-proc-def-id': 'contractor-onboarding-process.contractor-on-boarding',
      'task-container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      'task-parent-id': -1,
    },
    {
      'task-id': 5,
      'task-name': 'Contractor informations',
      'task-subject': null,
      'task-description': 'rh-contractor-onboarding-0000000003::',
      'task-status': 'Completed',
      'task-priority': 0,
      'task-is-skipable': false,
      'task-actual-owner': 'rhpamAdmin',
      'task-created-by': '',
      'task-created-on': {
        'java.util.Date': 1587033920019,
      },
      'task-activation-time': {
        'java.util.Date': 1587033920019,
      },
      'task-expiration-time': null,
      'task-proc-inst-id': 3,
      'task-proc-def-id': 'contractor-onboarding-process.contractor-on-boarding',
      'task-container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      'task-parent-id': -1,
    },
    {
      'task-id': 6,
      'task-name': 'Check contractor informations details',
      'task-subject': null,
      'task-description': 'rh-contractor-onboarding-0000000003::',
      'task-status': 'Reserved',
      'task-priority': 0,
      'task-is-skipable': false,
      'task-actual-owner': 'rhpamAdmin',
      'task-created-by': '',
      'task-created-on': {
        'java.util.Date': 1587033924957,
      },
      'task-activation-time': {
        'java.util.Date': 1587033924957,
      },
      'task-expiration-time': null,
      'task-proc-inst-id': 3,
      'task-proc-def-id': 'contractor-onboarding-process.contractor-on-boarding',
      'task-container-id': 'contractor-onboarding-process_1.0.0-SNAPSHOT',
      'task-parent-id': -1,
    },
  ],
};
